# Generated by Django 5.1.1 on 2024-10-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_blog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('finance', 'Finance')], default='technical', max_length=50)),
            ],
        ),
    ]
