# Generated by Django 5.1.1 on 2024-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_catogiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='categories/')),
                ('is_deleted', models.IntegerField(choices=[(0, 'Not Deleted'), (1, 'Deleted')], default=0)),
                ('is_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Catogiry',
        ),
    ]
