# Generated by Django 5.1.1 on 2024-10-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_blogcategory_delete_catogiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='is_status',
            new_name='status',
        ),
    ]
