# Generated by Django 5.1.1 on 2024-10-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.userregister'),
            preserve_default=False,
        ),
    ]
