# Generated by Django 5.1.1 on 2024-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catogiry_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
