# Generated by Django 5.1.1 on 2024-10-21 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='university',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='year_of_passing',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='blogapp.employee')),
            ],
        ),
    ]
