# Generated by Django 5.1.1 on 2024-10-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_remove_employee_course_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Emp',
        ),
    ]
