# Generated by Django 5.1.1 on 2024-10-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_rename_employee_emp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Educations',
        ),
    ]
