# Generated by Django 5.1.1 on 2024-10-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_rename_employee_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
