# Generated by Django 5.1.1 on 2024-10-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_emp_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='is_updated',
        ),
    ]
