# Generated by Django 5.1.1 on 2024-10-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_remove_emp_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
