# Generated by Django 5.1.1 on 2024-10-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_emp_is_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp',
            new_name='Emps',
        ),
    ]
