# Generated by Django 5.1.1 on 2024-10-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0026_rename_emp_emps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emps',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='university',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='year_of_passing',
        ),
        migrations.AddField(
            model_name='emps',
            name='education_details',
            field=models.JSONField(default=dict),
        ),
    ]
