# Generated by Django 5.1.1 on 2024-10-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_remove_emps_course_name_remove_emps_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emps',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='status',
        ),
    ]
