# Generated by Django 5.1.1 on 2024-10-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0028_remove_emps_is_created_remove_emps_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emps',
            name='deleted_status',
            field=models.IntegerField(choices=[(0, 'Not Deleted'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='emps',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emps',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
