# Generated by Django 5.1.1 on 2024-10-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0030_emps_is_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emps',
            name='is_created',
        ),
    ]
