# Generated by Django 5.1.1 on 2024-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_remove_emps_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='emps',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
