# Generated by Django 5.1.1 on 2024-10-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0037_emps_is_created_emps_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emps',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='is_updated',
        ),
    ]
