# Generated by Django 5.1.1 on 2024-10-26 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0039_emps_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='emps',
            name='is_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
