# Generated by Django 5.1.1 on 2024-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0040_emps_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emps',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
