# Generated by Django 5.1.1 on 2024-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0042_remove_emps_is_created_remove_emps_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='emps',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
